package cn.kcat.pojo;

import java.util.Date;

public class Major {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.id
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.majorName
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String majorname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.summary
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.imgPath
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String imgpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.delFlag
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private Integer delflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.createDate
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.modifyDate
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.refen1
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String refen1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.refen2
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String refen2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.refen3
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String refen3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.refen4
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String refen4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.refen5
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String refen5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.refen6
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String refen6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.refen7
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String refen7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.refen8
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String refen8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.refen9
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String refen9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.refen10
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String refen10;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.id
     *
     * @return the value of major.id
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.id
     *
     * @param id the value for major.id
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.majorName
     *
     * @return the value of major.majorName
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getMajorname() {
        return majorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.majorName
     *
     * @param majorname the value for major.majorName
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setMajorname(String majorname) {
        this.majorname = majorname == null ? null : majorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.summary
     *
     * @return the value of major.summary
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.summary
     *
     * @param summary the value for major.summary
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.imgPath
     *
     * @return the value of major.imgPath
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getImgpath() {
        return imgpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.imgPath
     *
     * @param imgpath the value for major.imgPath
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setImgpath(String imgpath) {
        this.imgpath = imgpath == null ? null : imgpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.delFlag
     *
     * @return the value of major.delFlag
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public Integer getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.delFlag
     *
     * @param delflag the value for major.delFlag
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setDelflag(Integer delflag) {
        this.delflag = delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.createDate
     *
     * @return the value of major.createDate
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.createDate
     *
     * @param createdate the value for major.createDate
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.modifyDate
     *
     * @return the value of major.modifyDate
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.modifyDate
     *
     * @param modifydate the value for major.modifyDate
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.refen1
     *
     * @return the value of major.refen1
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getRefen1() {
        return refen1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.refen1
     *
     * @param refen1 the value for major.refen1
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setRefen1(String refen1) {
        this.refen1 = refen1 == null ? null : refen1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.refen2
     *
     * @return the value of major.refen2
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getRefen2() {
        return refen2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.refen2
     *
     * @param refen2 the value for major.refen2
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setRefen2(String refen2) {
        this.refen2 = refen2 == null ? null : refen2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.refen3
     *
     * @return the value of major.refen3
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getRefen3() {
        return refen3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.refen3
     *
     * @param refen3 the value for major.refen3
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setRefen3(String refen3) {
        this.refen3 = refen3 == null ? null : refen3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.refen4
     *
     * @return the value of major.refen4
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getRefen4() {
        return refen4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.refen4
     *
     * @param refen4 the value for major.refen4
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setRefen4(String refen4) {
        this.refen4 = refen4 == null ? null : refen4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.refen5
     *
     * @return the value of major.refen5
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getRefen5() {
        return refen5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.refen5
     *
     * @param refen5 the value for major.refen5
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setRefen5(String refen5) {
        this.refen5 = refen5 == null ? null : refen5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.refen6
     *
     * @return the value of major.refen6
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getRefen6() {
        return refen6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.refen6
     *
     * @param refen6 the value for major.refen6
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setRefen6(String refen6) {
        this.refen6 = refen6 == null ? null : refen6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.refen7
     *
     * @return the value of major.refen7
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getRefen7() {
        return refen7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.refen7
     *
     * @param refen7 the value for major.refen7
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setRefen7(String refen7) {
        this.refen7 = refen7 == null ? null : refen7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.refen8
     *
     * @return the value of major.refen8
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getRefen8() {
        return refen8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.refen8
     *
     * @param refen8 the value for major.refen8
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setRefen8(String refen8) {
        this.refen8 = refen8 == null ? null : refen8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.refen9
     *
     * @return the value of major.refen9
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getRefen9() {
        return refen9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.refen9
     *
     * @param refen9 the value for major.refen9
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setRefen9(String refen9) {
        this.refen9 = refen9 == null ? null : refen9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.refen10
     *
     * @return the value of major.refen10
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getRefen10() {
        return refen10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.refen10
     *
     * @param refen10 the value for major.refen10
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setRefen10(String refen10) {
        this.refen10 = refen10 == null ? null : refen10.trim();
    }
}