package cn.kcat.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MajorsoftExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table majorsoft
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table majorsoft
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table majorsoft
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table majorsoft
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public MajorsoftExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table majorsoft
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table majorsoft
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table majorsoft
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table majorsoft
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table majorsoft
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table majorsoft
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table majorsoft
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table majorsoft
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table majorsoft
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table majorsoft
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table majorsoft
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andSummaryIsNull() {
            addCriterion("summary is null");
            return (Criteria) this;
        }

        public Criteria andSummaryIsNotNull() {
            addCriterion("summary is not null");
            return (Criteria) this;
        }

        public Criteria andSummaryEqualTo(String value) {
            addCriterion("summary =", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotEqualTo(String value) {
            addCriterion("summary <>", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryGreaterThan(String value) {
            addCriterion("summary >", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryGreaterThanOrEqualTo(String value) {
            addCriterion("summary >=", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLessThan(String value) {
            addCriterion("summary <", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLessThanOrEqualTo(String value) {
            addCriterion("summary <=", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLike(String value) {
            addCriterion("summary like", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotLike(String value) {
            addCriterion("summary not like", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryIn(List<String> values) {
            addCriterion("summary in", values, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotIn(List<String> values) {
            addCriterion("summary not in", values, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryBetween(String value1, String value2) {
            addCriterion("summary between", value1, value2, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotBetween(String value1, String value2) {
            addCriterion("summary not between", value1, value2, "summary");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("createDate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("createDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("createDate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("createDate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("createDate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("createDate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("createDate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("createDate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("createDate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("createDate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("createDate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("createDate not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNull() {
            addCriterion("modifyDate is null");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNotNull() {
            addCriterion("modifyDate is not null");
            return (Criteria) this;
        }

        public Criteria andModifydateEqualTo(Date value) {
            addCriterion("modifyDate =", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotEqualTo(Date value) {
            addCriterion("modifyDate <>", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThan(Date value) {
            addCriterion("modifyDate >", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThanOrEqualTo(Date value) {
            addCriterion("modifyDate >=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThan(Date value) {
            addCriterion("modifyDate <", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThanOrEqualTo(Date value) {
            addCriterion("modifyDate <=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateIn(List<Date> values) {
            addCriterion("modifyDate in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotIn(List<Date> values) {
            addCriterion("modifyDate not in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateBetween(Date value1, Date value2) {
            addCriterion("modifyDate between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotBetween(Date value1, Date value2) {
            addCriterion("modifyDate not between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andIconpathIsNull() {
            addCriterion("iconPath is null");
            return (Criteria) this;
        }

        public Criteria andIconpathIsNotNull() {
            addCriterion("iconPath is not null");
            return (Criteria) this;
        }

        public Criteria andIconpathEqualTo(String value) {
            addCriterion("iconPath =", value, "iconpath");
            return (Criteria) this;
        }

        public Criteria andIconpathNotEqualTo(String value) {
            addCriterion("iconPath <>", value, "iconpath");
            return (Criteria) this;
        }

        public Criteria andIconpathGreaterThan(String value) {
            addCriterion("iconPath >", value, "iconpath");
            return (Criteria) this;
        }

        public Criteria andIconpathGreaterThanOrEqualTo(String value) {
            addCriterion("iconPath >=", value, "iconpath");
            return (Criteria) this;
        }

        public Criteria andIconpathLessThan(String value) {
            addCriterion("iconPath <", value, "iconpath");
            return (Criteria) this;
        }

        public Criteria andIconpathLessThanOrEqualTo(String value) {
            addCriterion("iconPath <=", value, "iconpath");
            return (Criteria) this;
        }

        public Criteria andIconpathLike(String value) {
            addCriterion("iconPath like", value, "iconpath");
            return (Criteria) this;
        }

        public Criteria andIconpathNotLike(String value) {
            addCriterion("iconPath not like", value, "iconpath");
            return (Criteria) this;
        }

        public Criteria andIconpathIn(List<String> values) {
            addCriterion("iconPath in", values, "iconpath");
            return (Criteria) this;
        }

        public Criteria andIconpathNotIn(List<String> values) {
            addCriterion("iconPath not in", values, "iconpath");
            return (Criteria) this;
        }

        public Criteria andIconpathBetween(String value1, String value2) {
            addCriterion("iconPath between", value1, value2, "iconpath");
            return (Criteria) this;
        }

        public Criteria andIconpathNotBetween(String value1, String value2) {
            addCriterion("iconPath not between", value1, value2, "iconpath");
            return (Criteria) this;
        }

        public Criteria andDelflagIsNull() {
            addCriterion("delFlag is null");
            return (Criteria) this;
        }

        public Criteria andDelflagIsNotNull() {
            addCriterion("delFlag is not null");
            return (Criteria) this;
        }

        public Criteria andDelflagEqualTo(Integer value) {
            addCriterion("delFlag =", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagNotEqualTo(Integer value) {
            addCriterion("delFlag <>", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagGreaterThan(Integer value) {
            addCriterion("delFlag >", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagGreaterThanOrEqualTo(Integer value) {
            addCriterion("delFlag >=", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagLessThan(Integer value) {
            addCriterion("delFlag <", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagLessThanOrEqualTo(Integer value) {
            addCriterion("delFlag <=", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagIn(List<Integer> values) {
            addCriterion("delFlag in", values, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagNotIn(List<Integer> values) {
            addCriterion("delFlag not in", values, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagBetween(Integer value1, Integer value2) {
            addCriterion("delFlag between", value1, value2, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagNotBetween(Integer value1, Integer value2) {
            addCriterion("delFlag not between", value1, value2, "delflag");
            return (Criteria) this;
        }

        public Criteria andImgpathIsNull() {
            addCriterion("imgPath is null");
            return (Criteria) this;
        }

        public Criteria andImgpathIsNotNull() {
            addCriterion("imgPath is not null");
            return (Criteria) this;
        }

        public Criteria andImgpathEqualTo(String value) {
            addCriterion("imgPath =", value, "imgpath");
            return (Criteria) this;
        }

        public Criteria andImgpathNotEqualTo(String value) {
            addCriterion("imgPath <>", value, "imgpath");
            return (Criteria) this;
        }

        public Criteria andImgpathGreaterThan(String value) {
            addCriterion("imgPath >", value, "imgpath");
            return (Criteria) this;
        }

        public Criteria andImgpathGreaterThanOrEqualTo(String value) {
            addCriterion("imgPath >=", value, "imgpath");
            return (Criteria) this;
        }

        public Criteria andImgpathLessThan(String value) {
            addCriterion("imgPath <", value, "imgpath");
            return (Criteria) this;
        }

        public Criteria andImgpathLessThanOrEqualTo(String value) {
            addCriterion("imgPath <=", value, "imgpath");
            return (Criteria) this;
        }

        public Criteria andImgpathLike(String value) {
            addCriterion("imgPath like", value, "imgpath");
            return (Criteria) this;
        }

        public Criteria andImgpathNotLike(String value) {
            addCriterion("imgPath not like", value, "imgpath");
            return (Criteria) this;
        }

        public Criteria andImgpathIn(List<String> values) {
            addCriterion("imgPath in", values, "imgpath");
            return (Criteria) this;
        }

        public Criteria andImgpathNotIn(List<String> values) {
            addCriterion("imgPath not in", values, "imgpath");
            return (Criteria) this;
        }

        public Criteria andImgpathBetween(String value1, String value2) {
            addCriterion("imgPath between", value1, value2, "imgpath");
            return (Criteria) this;
        }

        public Criteria andImgpathNotBetween(String value1, String value2) {
            addCriterion("imgPath not between", value1, value2, "imgpath");
            return (Criteria) this;
        }

        public Criteria andIntroduceIsNull() {
            addCriterion("introduce is null");
            return (Criteria) this;
        }

        public Criteria andIntroduceIsNotNull() {
            addCriterion("introduce is not null");
            return (Criteria) this;
        }

        public Criteria andIntroduceEqualTo(String value) {
            addCriterion("introduce =", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceNotEqualTo(String value) {
            addCriterion("introduce <>", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceGreaterThan(String value) {
            addCriterion("introduce >", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceGreaterThanOrEqualTo(String value) {
            addCriterion("introduce >=", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceLessThan(String value) {
            addCriterion("introduce <", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceLessThanOrEqualTo(String value) {
            addCriterion("introduce <=", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceLike(String value) {
            addCriterion("introduce like", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceNotLike(String value) {
            addCriterion("introduce not like", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceIn(List<String> values) {
            addCriterion("introduce in", values, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceNotIn(List<String> values) {
            addCriterion("introduce not in", values, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceBetween(String value1, String value2) {
            addCriterion("introduce between", value1, value2, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceNotBetween(String value1, String value2) {
            addCriterion("introduce not between", value1, value2, "introduce");
            return (Criteria) this;
        }

        public Criteria andRefen1IsNull() {
            addCriterion("refen1 is null");
            return (Criteria) this;
        }

        public Criteria andRefen1IsNotNull() {
            addCriterion("refen1 is not null");
            return (Criteria) this;
        }

        public Criteria andRefen1EqualTo(String value) {
            addCriterion("refen1 =", value, "refen1");
            return (Criteria) this;
        }

        public Criteria andRefen1NotEqualTo(String value) {
            addCriterion("refen1 <>", value, "refen1");
            return (Criteria) this;
        }

        public Criteria andRefen1GreaterThan(String value) {
            addCriterion("refen1 >", value, "refen1");
            return (Criteria) this;
        }

        public Criteria andRefen1GreaterThanOrEqualTo(String value) {
            addCriterion("refen1 >=", value, "refen1");
            return (Criteria) this;
        }

        public Criteria andRefen1LessThan(String value) {
            addCriterion("refen1 <", value, "refen1");
            return (Criteria) this;
        }

        public Criteria andRefen1LessThanOrEqualTo(String value) {
            addCriterion("refen1 <=", value, "refen1");
            return (Criteria) this;
        }

        public Criteria andRefen1Like(String value) {
            addCriterion("refen1 like", value, "refen1");
            return (Criteria) this;
        }

        public Criteria andRefen1NotLike(String value) {
            addCriterion("refen1 not like", value, "refen1");
            return (Criteria) this;
        }

        public Criteria andRefen1In(List<String> values) {
            addCriterion("refen1 in", values, "refen1");
            return (Criteria) this;
        }

        public Criteria andRefen1NotIn(List<String> values) {
            addCriterion("refen1 not in", values, "refen1");
            return (Criteria) this;
        }

        public Criteria andRefen1Between(String value1, String value2) {
            addCriterion("refen1 between", value1, value2, "refen1");
            return (Criteria) this;
        }

        public Criteria andRefen1NotBetween(String value1, String value2) {
            addCriterion("refen1 not between", value1, value2, "refen1");
            return (Criteria) this;
        }

        public Criteria andRefen2IsNull() {
            addCriterion("refen2 is null");
            return (Criteria) this;
        }

        public Criteria andRefen2IsNotNull() {
            addCriterion("refen2 is not null");
            return (Criteria) this;
        }

        public Criteria andRefen2EqualTo(String value) {
            addCriterion("refen2 =", value, "refen2");
            return (Criteria) this;
        }

        public Criteria andRefen2NotEqualTo(String value) {
            addCriterion("refen2 <>", value, "refen2");
            return (Criteria) this;
        }

        public Criteria andRefen2GreaterThan(String value) {
            addCriterion("refen2 >", value, "refen2");
            return (Criteria) this;
        }

        public Criteria andRefen2GreaterThanOrEqualTo(String value) {
            addCriterion("refen2 >=", value, "refen2");
            return (Criteria) this;
        }

        public Criteria andRefen2LessThan(String value) {
            addCriterion("refen2 <", value, "refen2");
            return (Criteria) this;
        }

        public Criteria andRefen2LessThanOrEqualTo(String value) {
            addCriterion("refen2 <=", value, "refen2");
            return (Criteria) this;
        }

        public Criteria andRefen2Like(String value) {
            addCriterion("refen2 like", value, "refen2");
            return (Criteria) this;
        }

        public Criteria andRefen2NotLike(String value) {
            addCriterion("refen2 not like", value, "refen2");
            return (Criteria) this;
        }

        public Criteria andRefen2In(List<String> values) {
            addCriterion("refen2 in", values, "refen2");
            return (Criteria) this;
        }

        public Criteria andRefen2NotIn(List<String> values) {
            addCriterion("refen2 not in", values, "refen2");
            return (Criteria) this;
        }

        public Criteria andRefen2Between(String value1, String value2) {
            addCriterion("refen2 between", value1, value2, "refen2");
            return (Criteria) this;
        }

        public Criteria andRefen2NotBetween(String value1, String value2) {
            addCriterion("refen2 not between", value1, value2, "refen2");
            return (Criteria) this;
        }

        public Criteria andRefen3IsNull() {
            addCriterion("refen3 is null");
            return (Criteria) this;
        }

        public Criteria andRefen3IsNotNull() {
            addCriterion("refen3 is not null");
            return (Criteria) this;
        }

        public Criteria andRefen3EqualTo(String value) {
            addCriterion("refen3 =", value, "refen3");
            return (Criteria) this;
        }

        public Criteria andRefen3NotEqualTo(String value) {
            addCriterion("refen3 <>", value, "refen3");
            return (Criteria) this;
        }

        public Criteria andRefen3GreaterThan(String value) {
            addCriterion("refen3 >", value, "refen3");
            return (Criteria) this;
        }

        public Criteria andRefen3GreaterThanOrEqualTo(String value) {
            addCriterion("refen3 >=", value, "refen3");
            return (Criteria) this;
        }

        public Criteria andRefen3LessThan(String value) {
            addCriterion("refen3 <", value, "refen3");
            return (Criteria) this;
        }

        public Criteria andRefen3LessThanOrEqualTo(String value) {
            addCriterion("refen3 <=", value, "refen3");
            return (Criteria) this;
        }

        public Criteria andRefen3Like(String value) {
            addCriterion("refen3 like", value, "refen3");
            return (Criteria) this;
        }

        public Criteria andRefen3NotLike(String value) {
            addCriterion("refen3 not like", value, "refen3");
            return (Criteria) this;
        }

        public Criteria andRefen3In(List<String> values) {
            addCriterion("refen3 in", values, "refen3");
            return (Criteria) this;
        }

        public Criteria andRefen3NotIn(List<String> values) {
            addCriterion("refen3 not in", values, "refen3");
            return (Criteria) this;
        }

        public Criteria andRefen3Between(String value1, String value2) {
            addCriterion("refen3 between", value1, value2, "refen3");
            return (Criteria) this;
        }

        public Criteria andRefen3NotBetween(String value1, String value2) {
            addCriterion("refen3 not between", value1, value2, "refen3");
            return (Criteria) this;
        }

        public Criteria andRefen4IsNull() {
            addCriterion("refen4 is null");
            return (Criteria) this;
        }

        public Criteria andRefen4IsNotNull() {
            addCriterion("refen4 is not null");
            return (Criteria) this;
        }

        public Criteria andRefen4EqualTo(String value) {
            addCriterion("refen4 =", value, "refen4");
            return (Criteria) this;
        }

        public Criteria andRefen4NotEqualTo(String value) {
            addCriterion("refen4 <>", value, "refen4");
            return (Criteria) this;
        }

        public Criteria andRefen4GreaterThan(String value) {
            addCriterion("refen4 >", value, "refen4");
            return (Criteria) this;
        }

        public Criteria andRefen4GreaterThanOrEqualTo(String value) {
            addCriterion("refen4 >=", value, "refen4");
            return (Criteria) this;
        }

        public Criteria andRefen4LessThan(String value) {
            addCriterion("refen4 <", value, "refen4");
            return (Criteria) this;
        }

        public Criteria andRefen4LessThanOrEqualTo(String value) {
            addCriterion("refen4 <=", value, "refen4");
            return (Criteria) this;
        }

        public Criteria andRefen4Like(String value) {
            addCriterion("refen4 like", value, "refen4");
            return (Criteria) this;
        }

        public Criteria andRefen4NotLike(String value) {
            addCriterion("refen4 not like", value, "refen4");
            return (Criteria) this;
        }

        public Criteria andRefen4In(List<String> values) {
            addCriterion("refen4 in", values, "refen4");
            return (Criteria) this;
        }

        public Criteria andRefen4NotIn(List<String> values) {
            addCriterion("refen4 not in", values, "refen4");
            return (Criteria) this;
        }

        public Criteria andRefen4Between(String value1, String value2) {
            addCriterion("refen4 between", value1, value2, "refen4");
            return (Criteria) this;
        }

        public Criteria andRefen4NotBetween(String value1, String value2) {
            addCriterion("refen4 not between", value1, value2, "refen4");
            return (Criteria) this;
        }

        public Criteria andRefen5IsNull() {
            addCriterion("refen5 is null");
            return (Criteria) this;
        }

        public Criteria andRefen5IsNotNull() {
            addCriterion("refen5 is not null");
            return (Criteria) this;
        }

        public Criteria andRefen5EqualTo(String value) {
            addCriterion("refen5 =", value, "refen5");
            return (Criteria) this;
        }

        public Criteria andRefen5NotEqualTo(String value) {
            addCriterion("refen5 <>", value, "refen5");
            return (Criteria) this;
        }

        public Criteria andRefen5GreaterThan(String value) {
            addCriterion("refen5 >", value, "refen5");
            return (Criteria) this;
        }

        public Criteria andRefen5GreaterThanOrEqualTo(String value) {
            addCriterion("refen5 >=", value, "refen5");
            return (Criteria) this;
        }

        public Criteria andRefen5LessThan(String value) {
            addCriterion("refen5 <", value, "refen5");
            return (Criteria) this;
        }

        public Criteria andRefen5LessThanOrEqualTo(String value) {
            addCriterion("refen5 <=", value, "refen5");
            return (Criteria) this;
        }

        public Criteria andRefen5Like(String value) {
            addCriterion("refen5 like", value, "refen5");
            return (Criteria) this;
        }

        public Criteria andRefen5NotLike(String value) {
            addCriterion("refen5 not like", value, "refen5");
            return (Criteria) this;
        }

        public Criteria andRefen5In(List<String> values) {
            addCriterion("refen5 in", values, "refen5");
            return (Criteria) this;
        }

        public Criteria andRefen5NotIn(List<String> values) {
            addCriterion("refen5 not in", values, "refen5");
            return (Criteria) this;
        }

        public Criteria andRefen5Between(String value1, String value2) {
            addCriterion("refen5 between", value1, value2, "refen5");
            return (Criteria) this;
        }

        public Criteria andRefen5NotBetween(String value1, String value2) {
            addCriterion("refen5 not between", value1, value2, "refen5");
            return (Criteria) this;
        }

        public Criteria andRefen6IsNull() {
            addCriterion("refen6 is null");
            return (Criteria) this;
        }

        public Criteria andRefen6IsNotNull() {
            addCriterion("refen6 is not null");
            return (Criteria) this;
        }

        public Criteria andRefen6EqualTo(String value) {
            addCriterion("refen6 =", value, "refen6");
            return (Criteria) this;
        }

        public Criteria andRefen6NotEqualTo(String value) {
            addCriterion("refen6 <>", value, "refen6");
            return (Criteria) this;
        }

        public Criteria andRefen6GreaterThan(String value) {
            addCriterion("refen6 >", value, "refen6");
            return (Criteria) this;
        }

        public Criteria andRefen6GreaterThanOrEqualTo(String value) {
            addCriterion("refen6 >=", value, "refen6");
            return (Criteria) this;
        }

        public Criteria andRefen6LessThan(String value) {
            addCriterion("refen6 <", value, "refen6");
            return (Criteria) this;
        }

        public Criteria andRefen6LessThanOrEqualTo(String value) {
            addCriterion("refen6 <=", value, "refen6");
            return (Criteria) this;
        }

        public Criteria andRefen6Like(String value) {
            addCriterion("refen6 like", value, "refen6");
            return (Criteria) this;
        }

        public Criteria andRefen6NotLike(String value) {
            addCriterion("refen6 not like", value, "refen6");
            return (Criteria) this;
        }

        public Criteria andRefen6In(List<String> values) {
            addCriterion("refen6 in", values, "refen6");
            return (Criteria) this;
        }

        public Criteria andRefen6NotIn(List<String> values) {
            addCriterion("refen6 not in", values, "refen6");
            return (Criteria) this;
        }

        public Criteria andRefen6Between(String value1, String value2) {
            addCriterion("refen6 between", value1, value2, "refen6");
            return (Criteria) this;
        }

        public Criteria andRefen6NotBetween(String value1, String value2) {
            addCriterion("refen6 not between", value1, value2, "refen6");
            return (Criteria) this;
        }

        public Criteria andRefen7IsNull() {
            addCriterion("refen7 is null");
            return (Criteria) this;
        }

        public Criteria andRefen7IsNotNull() {
            addCriterion("refen7 is not null");
            return (Criteria) this;
        }

        public Criteria andRefen7EqualTo(String value) {
            addCriterion("refen7 =", value, "refen7");
            return (Criteria) this;
        }

        public Criteria andRefen7NotEqualTo(String value) {
            addCriterion("refen7 <>", value, "refen7");
            return (Criteria) this;
        }

        public Criteria andRefen7GreaterThan(String value) {
            addCriterion("refen7 >", value, "refen7");
            return (Criteria) this;
        }

        public Criteria andRefen7GreaterThanOrEqualTo(String value) {
            addCriterion("refen7 >=", value, "refen7");
            return (Criteria) this;
        }

        public Criteria andRefen7LessThan(String value) {
            addCriterion("refen7 <", value, "refen7");
            return (Criteria) this;
        }

        public Criteria andRefen7LessThanOrEqualTo(String value) {
            addCriterion("refen7 <=", value, "refen7");
            return (Criteria) this;
        }

        public Criteria andRefen7Like(String value) {
            addCriterion("refen7 like", value, "refen7");
            return (Criteria) this;
        }

        public Criteria andRefen7NotLike(String value) {
            addCriterion("refen7 not like", value, "refen7");
            return (Criteria) this;
        }

        public Criteria andRefen7In(List<String> values) {
            addCriterion("refen7 in", values, "refen7");
            return (Criteria) this;
        }

        public Criteria andRefen7NotIn(List<String> values) {
            addCriterion("refen7 not in", values, "refen7");
            return (Criteria) this;
        }

        public Criteria andRefen7Between(String value1, String value2) {
            addCriterion("refen7 between", value1, value2, "refen7");
            return (Criteria) this;
        }

        public Criteria andRefen7NotBetween(String value1, String value2) {
            addCriterion("refen7 not between", value1, value2, "refen7");
            return (Criteria) this;
        }

        public Criteria andRefen8IsNull() {
            addCriterion("refen8 is null");
            return (Criteria) this;
        }

        public Criteria andRefen8IsNotNull() {
            addCriterion("refen8 is not null");
            return (Criteria) this;
        }

        public Criteria andRefen8EqualTo(String value) {
            addCriterion("refen8 =", value, "refen8");
            return (Criteria) this;
        }

        public Criteria andRefen8NotEqualTo(String value) {
            addCriterion("refen8 <>", value, "refen8");
            return (Criteria) this;
        }

        public Criteria andRefen8GreaterThan(String value) {
            addCriterion("refen8 >", value, "refen8");
            return (Criteria) this;
        }

        public Criteria andRefen8GreaterThanOrEqualTo(String value) {
            addCriterion("refen8 >=", value, "refen8");
            return (Criteria) this;
        }

        public Criteria andRefen8LessThan(String value) {
            addCriterion("refen8 <", value, "refen8");
            return (Criteria) this;
        }

        public Criteria andRefen8LessThanOrEqualTo(String value) {
            addCriterion("refen8 <=", value, "refen8");
            return (Criteria) this;
        }

        public Criteria andRefen8Like(String value) {
            addCriterion("refen8 like", value, "refen8");
            return (Criteria) this;
        }

        public Criteria andRefen8NotLike(String value) {
            addCriterion("refen8 not like", value, "refen8");
            return (Criteria) this;
        }

        public Criteria andRefen8In(List<String> values) {
            addCriterion("refen8 in", values, "refen8");
            return (Criteria) this;
        }

        public Criteria andRefen8NotIn(List<String> values) {
            addCriterion("refen8 not in", values, "refen8");
            return (Criteria) this;
        }

        public Criteria andRefen8Between(String value1, String value2) {
            addCriterion("refen8 between", value1, value2, "refen8");
            return (Criteria) this;
        }

        public Criteria andRefen8NotBetween(String value1, String value2) {
            addCriterion("refen8 not between", value1, value2, "refen8");
            return (Criteria) this;
        }

        public Criteria andRefen9IsNull() {
            addCriterion("refen9 is null");
            return (Criteria) this;
        }

        public Criteria andRefen9IsNotNull() {
            addCriterion("refen9 is not null");
            return (Criteria) this;
        }

        public Criteria andRefen9EqualTo(String value) {
            addCriterion("refen9 =", value, "refen9");
            return (Criteria) this;
        }

        public Criteria andRefen9NotEqualTo(String value) {
            addCriterion("refen9 <>", value, "refen9");
            return (Criteria) this;
        }

        public Criteria andRefen9GreaterThan(String value) {
            addCriterion("refen9 >", value, "refen9");
            return (Criteria) this;
        }

        public Criteria andRefen9GreaterThanOrEqualTo(String value) {
            addCriterion("refen9 >=", value, "refen9");
            return (Criteria) this;
        }

        public Criteria andRefen9LessThan(String value) {
            addCriterion("refen9 <", value, "refen9");
            return (Criteria) this;
        }

        public Criteria andRefen9LessThanOrEqualTo(String value) {
            addCriterion("refen9 <=", value, "refen9");
            return (Criteria) this;
        }

        public Criteria andRefen9Like(String value) {
            addCriterion("refen9 like", value, "refen9");
            return (Criteria) this;
        }

        public Criteria andRefen9NotLike(String value) {
            addCriterion("refen9 not like", value, "refen9");
            return (Criteria) this;
        }

        public Criteria andRefen9In(List<String> values) {
            addCriterion("refen9 in", values, "refen9");
            return (Criteria) this;
        }

        public Criteria andRefen9NotIn(List<String> values) {
            addCriterion("refen9 not in", values, "refen9");
            return (Criteria) this;
        }

        public Criteria andRefen9Between(String value1, String value2) {
            addCriterion("refen9 between", value1, value2, "refen9");
            return (Criteria) this;
        }

        public Criteria andRefen9NotBetween(String value1, String value2) {
            addCriterion("refen9 not between", value1, value2, "refen9");
            return (Criteria) this;
        }

        public Criteria andRefen10IsNull() {
            addCriterion("refen10 is null");
            return (Criteria) this;
        }

        public Criteria andRefen10IsNotNull() {
            addCriterion("refen10 is not null");
            return (Criteria) this;
        }

        public Criteria andRefen10EqualTo(String value) {
            addCriterion("refen10 =", value, "refen10");
            return (Criteria) this;
        }

        public Criteria andRefen10NotEqualTo(String value) {
            addCriterion("refen10 <>", value, "refen10");
            return (Criteria) this;
        }

        public Criteria andRefen10GreaterThan(String value) {
            addCriterion("refen10 >", value, "refen10");
            return (Criteria) this;
        }

        public Criteria andRefen10GreaterThanOrEqualTo(String value) {
            addCriterion("refen10 >=", value, "refen10");
            return (Criteria) this;
        }

        public Criteria andRefen10LessThan(String value) {
            addCriterion("refen10 <", value, "refen10");
            return (Criteria) this;
        }

        public Criteria andRefen10LessThanOrEqualTo(String value) {
            addCriterion("refen10 <=", value, "refen10");
            return (Criteria) this;
        }

        public Criteria andRefen10Like(String value) {
            addCriterion("refen10 like", value, "refen10");
            return (Criteria) this;
        }

        public Criteria andRefen10NotLike(String value) {
            addCriterion("refen10 not like", value, "refen10");
            return (Criteria) this;
        }

        public Criteria andRefen10In(List<String> values) {
            addCriterion("refen10 in", values, "refen10");
            return (Criteria) this;
        }

        public Criteria andRefen10NotIn(List<String> values) {
            addCriterion("refen10 not in", values, "refen10");
            return (Criteria) this;
        }

        public Criteria andRefen10Between(String value1, String value2) {
            addCriterion("refen10 between", value1, value2, "refen10");
            return (Criteria) this;
        }

        public Criteria andRefen10NotBetween(String value1, String value2) {
            addCriterion("refen10 not between", value1, value2, "refen10");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table majorsoft
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 18 22:27:57 SGT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table majorsoft
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}