package cn.kcat.pojo;

import java.util.Date;

public class MajorToMajorsoft {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_to_majorsoft.id
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_to_majorsoft.majorCode
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String majorcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_to_majorsoft.majorSoftCode
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String majorsoftcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_to_majorsoft.summary
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_to_majorsoft.delFlag
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private Integer delflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_to_majorsoft.imgPath
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String imgpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_to_majorsoft.createDate
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_to_majorsoft.modifyDate
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_to_majorsoft.refen1
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String refen1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_to_majorsoft.refen2
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String refen2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_to_majorsoft.refen3
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String refen3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_to_majorsoft.refen4
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String refen4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_to_majorsoft.refen5
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String refen5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_to_majorsoft.refen6
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String refen6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_to_majorsoft.refen7
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String refen7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_to_majorsoft.refen8
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String refen8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_to_majorsoft.refen9
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String refen9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_to_majorsoft.refen10
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    private String refen10;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_to_majorsoft.id
     *
     * @return the value of major_to_majorsoft.id
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_to_majorsoft.id
     *
     * @param id the value for major_to_majorsoft.id
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_to_majorsoft.majorCode
     *
     * @return the value of major_to_majorsoft.majorCode
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getMajorcode() {
        return majorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_to_majorsoft.majorCode
     *
     * @param majorcode the value for major_to_majorsoft.majorCode
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setMajorcode(String majorcode) {
        this.majorcode = majorcode == null ? null : majorcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_to_majorsoft.majorSoftCode
     *
     * @return the value of major_to_majorsoft.majorSoftCode
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getMajorsoftcode() {
        return majorsoftcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_to_majorsoft.majorSoftCode
     *
     * @param majorsoftcode the value for major_to_majorsoft.majorSoftCode
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setMajorsoftcode(String majorsoftcode) {
        this.majorsoftcode = majorsoftcode == null ? null : majorsoftcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_to_majorsoft.summary
     *
     * @return the value of major_to_majorsoft.summary
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_to_majorsoft.summary
     *
     * @param summary the value for major_to_majorsoft.summary
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_to_majorsoft.delFlag
     *
     * @return the value of major_to_majorsoft.delFlag
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public Integer getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_to_majorsoft.delFlag
     *
     * @param delflag the value for major_to_majorsoft.delFlag
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setDelflag(Integer delflag) {
        this.delflag = delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_to_majorsoft.imgPath
     *
     * @return the value of major_to_majorsoft.imgPath
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getImgpath() {
        return imgpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_to_majorsoft.imgPath
     *
     * @param imgpath the value for major_to_majorsoft.imgPath
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setImgpath(String imgpath) {
        this.imgpath = imgpath == null ? null : imgpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_to_majorsoft.createDate
     *
     * @return the value of major_to_majorsoft.createDate
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_to_majorsoft.createDate
     *
     * @param createdate the value for major_to_majorsoft.createDate
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_to_majorsoft.modifyDate
     *
     * @return the value of major_to_majorsoft.modifyDate
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_to_majorsoft.modifyDate
     *
     * @param modifydate the value for major_to_majorsoft.modifyDate
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_to_majorsoft.refen1
     *
     * @return the value of major_to_majorsoft.refen1
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getRefen1() {
        return refen1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_to_majorsoft.refen1
     *
     * @param refen1 the value for major_to_majorsoft.refen1
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setRefen1(String refen1) {
        this.refen1 = refen1 == null ? null : refen1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_to_majorsoft.refen2
     *
     * @return the value of major_to_majorsoft.refen2
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getRefen2() {
        return refen2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_to_majorsoft.refen2
     *
     * @param refen2 the value for major_to_majorsoft.refen2
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setRefen2(String refen2) {
        this.refen2 = refen2 == null ? null : refen2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_to_majorsoft.refen3
     *
     * @return the value of major_to_majorsoft.refen3
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getRefen3() {
        return refen3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_to_majorsoft.refen3
     *
     * @param refen3 the value for major_to_majorsoft.refen3
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setRefen3(String refen3) {
        this.refen3 = refen3 == null ? null : refen3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_to_majorsoft.refen4
     *
     * @return the value of major_to_majorsoft.refen4
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getRefen4() {
        return refen4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_to_majorsoft.refen4
     *
     * @param refen4 the value for major_to_majorsoft.refen4
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setRefen4(String refen4) {
        this.refen4 = refen4 == null ? null : refen4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_to_majorsoft.refen5
     *
     * @return the value of major_to_majorsoft.refen5
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getRefen5() {
        return refen5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_to_majorsoft.refen5
     *
     * @param refen5 the value for major_to_majorsoft.refen5
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setRefen5(String refen5) {
        this.refen5 = refen5 == null ? null : refen5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_to_majorsoft.refen6
     *
     * @return the value of major_to_majorsoft.refen6
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getRefen6() {
        return refen6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_to_majorsoft.refen6
     *
     * @param refen6 the value for major_to_majorsoft.refen6
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setRefen6(String refen6) {
        this.refen6 = refen6 == null ? null : refen6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_to_majorsoft.refen7
     *
     * @return the value of major_to_majorsoft.refen7
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getRefen7() {
        return refen7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_to_majorsoft.refen7
     *
     * @param refen7 the value for major_to_majorsoft.refen7
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setRefen7(String refen7) {
        this.refen7 = refen7 == null ? null : refen7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_to_majorsoft.refen8
     *
     * @return the value of major_to_majorsoft.refen8
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getRefen8() {
        return refen8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_to_majorsoft.refen8
     *
     * @param refen8 the value for major_to_majorsoft.refen8
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setRefen8(String refen8) {
        this.refen8 = refen8 == null ? null : refen8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_to_majorsoft.refen9
     *
     * @return the value of major_to_majorsoft.refen9
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getRefen9() {
        return refen9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_to_majorsoft.refen9
     *
     * @param refen9 the value for major_to_majorsoft.refen9
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setRefen9(String refen9) {
        this.refen9 = refen9 == null ? null : refen9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_to_majorsoft.refen10
     *
     * @return the value of major_to_majorsoft.refen10
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public String getRefen10() {
        return refen10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_to_majorsoft.refen10
     *
     * @param refen10 the value for major_to_majorsoft.refen10
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    public void setRefen10(String refen10) {
        this.refen10 = refen10 == null ? null : refen10.trim();
    }
}