package cn.kcat.mapper;

import cn.kcat.pojo.Major;
import cn.kcat.pojo.MajorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MajorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    int countByExample(MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    int deleteByExample(MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    int insert(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    int insertSelective(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    List<Major> selectByExample(MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    Major selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    int updateByExampleSelective(@Param("record") Major record, @Param("example") MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    int updateByExample(@Param("record") Major record, @Param("example") MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    int updateByPrimaryKeySelective(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated Wed Apr 18 22:27:57 SGT 2018
     */
    int updateByPrimaryKey(Major record);
}